type ExtraCatalogGroup = {
  category: string;
  area: { en: string; "pt-BR": string };
  terms: string[];
};

export const extraCatalogGroups: ExtraCatalogGroup[] = [
  {
    category: "frontend",
    area: {
      en: "frontend engineering and web interfaces",
      "pt-BR": "engenharia frontend e interfaces web",
    },
    terms: [
      "Frontend",
      "Backend",
      "Full Stack",
      "Client-side",
      "Server-side",
      "Rendering",
      "Client-Side Rendering",
      "Server-Side Rendering",
      "Static Site Generation",
      "Incremental Static Regeneration",
      "Hydration",
      "DOM",
      "Virtual DOM",
      "Component",
      "State",
      "Props",
      "Hook",
      "Context",
      "State Management",
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Responsive Design",
      "Mobile First",
      "Progressive Web App",
      "Single Page Application",
      "Multi-Page Application",
      "Bundle",
      "Bundler",
      "Tree Shaking",
      "Lazy Loading",
      "Code Splitting",
      "Accessibility",
      "Semantic HTML",
      "CSS",
      "CSS Module",
      "Tailwind CSS",
      "Design System",
      "Storybook",
    ],
  },
  {
    category: "design",
    area: {
      en: "product design, UX, and interface systems",
      "pt-BR": "design de produto, UX e sistemas de interface",
    },
    terms: [
      "User Experience",
      "User Interface",
      "UX",
      "UI",
      "Prototype",
      "Mockup",
      "Design Token",
      "Component Library",
      "Usability",
      "User Flow",
      "Information Architecture",
      "Interaction Design",
      "Visual Hierarchy",
      "Affordance",
      "Feedback Visual",
      "Empty State",
      "Loading State",
      "Error State",
      "Skeleton Screen",
      "Responsive Breakpoint",
      "Grid System",
      "Typography",
      "Contrast",
      "Color Palette",
      "Accessibility Audit",
      "Heuristic Evaluation",
      "Design Handoff",
      "Figma",
      "Atomic Design",
    ],
  },
  {
    category: "documentation",
    area: {
      en: "technical documentation and shared engineering knowledge",
      "pt-BR":
        "documentação técnica e conhecimento compartilhado de engenharia",
    },
    terms: [
      "Technical Documentation",
      "API Documentation",
      "OpenAPI",
      "Swagger",
      "README",
      "ADR",
      "Architecture Decision Record",
      "RFC",
      "Runbook",
      "Playbook",
      "Changelog",
      "Release Notes",
      "Sequence Diagram",
      "Component Diagram",
      "C4 Model",
      "Data Dictionary",
      "Technical Specification",
      "Functional Specification",
      "Definition of Ready",
      "Definition of Done",
      "Knowledge Base",
      "Postmortem",
      "Incident Report",
      "Troubleshooting Guide",
      "Onboarding Documentation",
    ],
  },
  {
    category: "observability",
    area: {
      en: "observability, production operations, and incident response",
      "pt-BR": "observabilidade, operação de produção e resposta a incidentes",
    },
    terms: [
      "Observability",
      "Monitoring",
      "Logging",
      "Metrics",
      "Tracing",
      "Distributed Tracing",
      "Telemetry",
      "Dashboard",
      "Alert",
      "Alerting",
      "Log Level",
      "Structured Logging",
      "Correlation ID",
      "Trace ID",
      "Service Level Indicator",
      "Service Level Objective",
      "SLI",
      "SLO",
      "Error Budget",
      "Mean Time to Detect",
      "Mean Time to Recovery",
      "MTTD",
      "MTTR",
      "Incident",
      "Production Incident",
      "Incident Management",
      "Incident Response",
      "On-call",
      "Escalation",
      "Postmortem",
      "Root Cause Analysis",
      "Blameless Postmortem",
      "Runbook",
      "Playbook",
      "Outage",
      "Degradation",
      "Availability Zone",
      "Disaster Recovery",
      "Business Continuity",
      "Recovery Point Objective",
      "Recovery Time Objective",
      "RPO",
      "RTO",
    ],
  },
  {
    category: "messaging",
    area: {
      en: "messaging and asynchronous processing",
      "pt-BR": "mensageria e processamento assíncrono",
    },
    terms: [
      "Message",
      "Message Broker",
      "Messaging",
      "Producer",
      "Consumer",
      "Publisher",
      "Subscriber",
      "Publish/Subscribe",
      "Pub/Sub",
      "Queue",
      "Topic",
      "Exchange",
      "Routing Key",
      "Dead Letter Queue",
      "DLQ",
      "Retry",
      "Backoff",
      "Exponential Backoff",
      "Acknowledgement",
      "At-Most-Once Delivery",
      "At-Least-Once Delivery",
      "Exactly-Once Semantics",
      "Event",
      "Event Bus",
      "Event Stream",
      "Event Sourcing",
      "CQRS",
      "Saga",
      "Orchestration",
      "Choreography",
      "Outbox Pattern",
      "Inbox Pattern",
      "RabbitMQ",
      "Apache Kafka",
      "BullMQ",
      "Background Job",
      "Worker",
      "Job",
      "Scheduler",
      "Cron Job",
    ],
  },
  {
    category: "distributed-systems",
    area: {
      en: "distributed systems and resilience engineering",
      "pt-BR": "sistemas distribuídos e engenharia de resiliência",
    },
    terms: [
      "Distributed Computing",
      "Distributed Lock",
      "Leader Election",
      "Consensus",
      "Quorum",
      "CAP Theorem",
      "Eventual Consistency",
      "Strong Consistency",
      "Network Partition",
      "Split Brain",
      "Circuit Breaker",
      "Timeout",
      "Retry Policy",
      "Bulkhead",
      "Fallback",
      "Failover",
      "Redundancy",
      "Fault Tolerance",
      "Resilience",
      "Backpressure",
      "Throttling",
      "Load Shedding",
      "Graceful Degradation",
      "Graceful Shutdown",
      "Service Discovery",
      "Configuration Server",
      "Distributed Cache",
      "Distributed Transaction",
      "Two-Phase Commit",
      "Compensating Transaction",
      "Clock Skew",
      "Race Condition",
      "Concurrency",
      "Parallelism",
      "Mutex",
      "Semaphore",
    ],
  },
  {
    category: "performance",
    area: {
      en: "software performance and capacity engineering",
      "pt-BR": "performance de software e engenharia de capacidade",
    },
    terms: [
      "Performance",
      "Latency",
      "Throughput",
      "Response Time",
      "Benchmark",
      "Profiling",
      "Optimization",
      "Memory Leak",
      "CPU Bound",
      "I/O Bound",
      "Bottleneck Analysis",
      "Caching Strategy",
      "Cache Hit",
      "Cache Miss",
      "Cache Invalidation",
      "Compression",
      "Gzip",
      "Brotli",
      "Connection Keep-Alive",
      "N+1 Query",
      "Slow Query",
      "Query Plan",
      "Execution Plan",
      "Database Partitioning",
      "Horizontal Partitioning",
      "Vertical Partitioning",
      "Read Replica",
      "Write Through",
      "Write Back",
      "Load Testing",
      "Stress Testing",
      "Spike Testing",
      "Soak Testing",
      "Capacity Planning",
    ],
  },
  {
    category: "security",
    area: {
      en: "applied security and identity management",
      "pt-BR": "segurança aplicada e gestão de identidade",
    },
    terms: [
      "Identity",
      "Identity Provider",
      "IdP",
      "Single Sign-On",
      "SSO",
      "OpenID Connect",
      "OIDC",
      "Permission",
      "Role",
      "Policy",
      "Claim",
      "Scope",
      "Refresh Token",
      "Access Token",
      "Session Hijacking",
      "Credential Stuffing",
      "Replay Attack",
      "Man-in-the-Middle",
      "MITM",
      "Security Header",
      "Content Security Policy",
      "CSP",
      "SameSite",
      "Secure Cookie",
      "HttpOnly",
      "Secret Management",
      "Key Rotation",
      "Certificate",
      "Public Key",
      "Private Key",
      "Symmetric Encryption",
      "Asymmetric Encryption",
      "Digital Signature",
      "HMAC",
      "Data Masking",
      "Tokenization",
      "Penetration Test",
      "Threat Modeling",
      "OWASP",
      "OWASP Top 10",
      "Security Audit",
      "Compliance",
      "Vulnerability Scan",
    ],
  },
  {
    category: "integrations",
    area: {
      en: "system integrations and API contracts",
      "pt-BR": "integrações de sistemas e contratos de API",
    },
    terms: [
      "Integration",
      "Third-Party Integration",
      "External Service",
      "SDK",
      "Client Library",
      "Contract",
      "API Contract",
      "Consumer",
      "Provider",
      "Request Signing",
      "Webhook Signature",
      "Retry Policy",
      "Timeout",
      "Circuit Breaker",
      "API Versioning",
      "Deprecation",
      "Backward Compatibility",
      "Forward Compatibility",
      "Breaking Change",
      "Schema Validation",
      "Contract Test",
      "Consumer-Driven Contract",
      "Mock Server",
      "Sandbox Environment",
      "Rate Limiting",
      "Throttling",
      "API Documentation",
      "API Gateway",
      "BFF",
      "Backend for Frontend",
      "GraphQL",
      "gRPC",
      "SOAP",
      "REST",
      "RPC",
    ],
  },
  {
    category: "data",
    area: {
      en: "data engineering, governance, and analytics",
      "pt-BR": "engenharia, governança e análise de dados",
    },
    terms: [
      "Data",
      "Dataset",
      "Data Pipeline",
      "ETL",
      "ELT",
      "Data Warehouse",
      "Data Lake",
      "Data Lakehouse",
      "Data Mart",
      "Data Modeling",
      "Data Governance",
      "Data Quality",
      "Master Data",
      "Metadata",
      "Analytics",
      "Business Intelligence",
      "BI",
      "Dashboard",
      "Report",
      "Event Tracking",
      "Analytics Event",
      "Funnel",
      "Cohort",
      "Conversion Rate",
      "Retention Rate",
      "Data Migration",
      "Batch Processing",
      "Stream Processing",
      "Change Data Capture",
      "CDC",
    ],
  },
  {
    category: "corporate-systems",
    area: {
      en: "enterprise systems and digital business models",
      "pt-BR": "sistemas corporativos e modelos de negócio digitais",
    },
    terms: [
      "Enterprise System",
      "Core System",
      "Backoffice",
      "Admin Panel",
      "ERP",
      "CRM",
      "CMS",
      "WMS",
      "TMS",
      "HRIS",
      "POS",
      "Payment Gateway",
      "Payment Processor",
      "Acquirer",
      "Issuer",
      "Banking as a Service",
      "BaaS",
      "Platform as a Service",
      "PaaS",
      "Infrastructure as a Service",
      "IaaS",
      "Software as a Service",
      "SaaS",
      "Subscription",
      "Recurring Billing",
      "Transaction Fee",
      "Commission",
      "Revenue",
      "Gross Revenue",
      "Net Revenue",
      "Margin",
      "Unit Economics",
      "Customer Acquisition Cost",
      "CAC",
      "Lifetime Value",
      "LTV",
      "Gross Merchandise Value",
      "GMV",
      "Multi-tenant",
      "Tenant",
      "White Label",
      "Marketplace",
      "Fintech",
    ],
  },
  {
    category: "product",
    area: {
      en: "product strategy, management, and delivery",
      "pt-BR": "estratégia, gestão e entrega de produto",
    },
    terms: [
      "Product Discovery",
      "Product Delivery",
      "Product-Market Fit",
      "PMF",
      "Go-to-Market",
      "GTM",
      "User Persona",
      "Customer Journey",
      "User Journey",
      "Job to Be Done",
      "JTBD",
      "Hypothesis",
      "Experiment",
      "A/B Test",
      "Feature Flag",
      "Rollout",
      "Adoption",
      "Engagement",
      "North Star Metric",
      "Leading Indicator",
      "Lagging Indicator",
      "Milestone",
      "Dependency Mapping",
      "Risk",
      "Risk Assessment",
      "Impact",
      "Effort",
      "Impact vs Effort",
      "Prioritization Matrix",
      "RICE",
      "MoSCoW",
      "Technical Roadmap",
      "Product Roadmap",
      "Stakeholder Management",
      "Change Management",
      "Delivery",
      "Delivery Lead",
      "Project Manager",
      "Scrum Master",
      "Tech Lead",
      "Engineering Manager",
      "Staff Engineer",
      "Principal Engineer",
      "CTO",
      "CIO",
    ],
  },
  {
    category: "git",
    area: {
      en: "source control and collaborative code delivery",
      "pt-BR": "controle de versão e entrega colaborativa de código",
    },
    terms: [
      "Source Control",
      "Version Control",
      "Working Tree",
      "Staging Area",
      "Index",
      "Local Repository",
      "Remote Repository",
      "Upstream",
      "Downstream",
      "Tracking Branch",
      "Detached HEAD",
      "Fast-forward",
      "Squash",
      "Squash Merge",
      "Merge Commit",
      "Revert",
      "Reset",
      "Soft Reset",
      "Mixed Reset",
      "Hard Reset",
      "Amend",
      "Git Hook",
      "Pre-commit Hook",
      "Protected Branch",
      "Branch Protection",
      "Code Owner",
      "CODEOWNERS",
      "Draft Pull Request",
      "Approval",
      "Review Comment",
      "Rebase Interactive",
      "Git Bisect",
      "Git Blame",
      "Git Tag",
      "Release Branch",
      "Feature Branch",
      "Trunk-Based Development",
      "Monorepo",
      "Polyrepo",
    ],
  },
];
